### ISSUE TITLE
No web interface in kodi

### ISSUE THREAD

**Issue by raintwoto** [avafinger/nanopi-m4-ubuntu-base-minimal#13]
I can not find the web interface in kodi. I don't know if you hide it. Could you restore it, so that I can control Jodi using my phone

**Comment by avafinger** [comment]
It was not compiled in this Kodi build.
Please, refer to https://github.com/avafinger/nanopi-m4-ubuntu-base-minimal/issues/10#issuecomment-472107294

Use Kernel 4.4.177-rk3399 for that. It will take some time for me to build Kodi 19 but will be done sooner or later.

**Comment by avafinger** [comment]
Ok, i just compiled Kodi 19.0 ALPHA1 with the Web Interface,

https://github.com/avafinger/nanopi-m4-ubuntu-base-minimal#building-kodi-19
