### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by ghost** [avafinger/nanopi-m4-ubuntu-base-minimal#20]
Hi! I have been testing m4 on mainline woth armbian. I never achieved vpu acceleration while hantro modele It's confirmed to be there. How I need to compile ffmpeg to get hantro to run at least h264 format?? What other formats it can decode?? Thanks on advance.

**Comment by avafinger** [comment]
I will try to test VPU this weekend and see what i get. (mairline)

**Comment by ghost** [comment]
So, the problem seems to be than the fork of ffmpeg than gives you hw acceleration demands another patches, not just hantro. I am utilizing the most mainline images available for rk3399 on armbian with balbes images. It seems than that patch must be done manually. I thought it was already there and it's not, no matter than hantro it's present. So.. I will not have another option than use your images (I mean, I am not that ok with not having focal). I don't know how to apply a patch on armbian build script, but if you know how it would be cool if you inform me how. Compile the kernel from the board itself it's not an option bc armbian won't use the new kernel. I tried that too.

**Comment by avafinger** [comment]
I am building one IMG today, so you can test it and compare.

**Comment by ghost** [comment]
Thankss!

**Comment by avafinger** [comment]
You can test it: https://github.com/avafinger/nanopi-m4-ubuntu-base-minimal/releases/tag/v1.36

**Comment by ghost** [comment]
It didn't boot. No problem. I will just install legacy. Thanks for the effort
