### ISSUE TITLE
Pardon my ignorance, but how do I install this kernel?

### ISSUE THREAD

**Issue by mikegleasonjr** [avafinger/nanopi-m4-ubuntu-base-minimal#5]
I am running the latest FriendlyElec distro on my M4.

When I install the .deb I have this error: `ERROR: No kernel Image here!`

Thank you

**Comment by avafinger** [comment]
This kernel image is not for FriendlyElec distro or any other distro.
You need to flash **this OS Image** and then upgrade the kernel image.

Burn the SD card with this **img**:
https://mega.nz/#!YLZhlYJb!uqvCIjpeBoGyfhaNYPJwb67kma7wmGTn5ZObe-CPrb4

Boot with this SD card, make your adjustments to connect to the internet (DHCP), you may need to update **/etc/resolv.conf**  before you boot (edit the file and put your DNS resolver, check your /etc/resolv.conf from your current PC).

**Comment by mikegleasonjr** [comment]
Thanks!
