### ISSUE TITLE
No need to package a idbloader for eMMC

### ISSUE THREAD

**Issue by oiramario** [avafinger/nanopi-m4-ubuntu-base-minimal#7]
@flash_kodi_emmc.sh

...
pt_warn "Writting u-boot $out ..."
**sudo dd if=./idbloader.img of=${out} seek=64 conv=notrunc**
sync
sudo dd if=./trust.img of=${out} seek=24576 conv=notrunc
sync
sudo dd if=./uboot.img of=${out} seek=16384 conv=notrunc
sync
...

**Comment by avafinger** [comment]
Please, explain your claim.

**Comment by oiramario** [comment]
http://opensource.rock-chips.com/wiki_Boot_option#The_Pre-bootloader
http://opensource.rock-chips.com/wiki_Boot_option#Boot_from_eMMC
