### ISSUE TITLE
Kernel Configuration file release

### ISSUE THREAD

**Issue by lorefx** [avafinger/nanopi-m4-ubuntu-base-minimal#9]
Hello, it would be really appreciated to have you release the kernel configuration file along with each release, so everyone can do its own modifications to the kernel without asking to you.

**Comment by avafinger** [comment]
Here is the defconfig i use. I had forgotten to include **TUN=y**

[nanopim4_defconfig.tar.gz](https://github.com/avafinger/nanopi-m4-ubuntu-base-minimal/files/2953801/nanopim4_defconfig.tar.gz)

**Comment by lorefx** [comment]
Thank you very much!
